version: '3.0'
services:
  database:
    image: mysql:latest
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - starter_kit_db:/var/lib/mysql
      - './db/init-script.sh:/docker-entrypoint-initdb.d/init-script.sh:ro,exec'
    networks:
      - app_net

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app_net

  web:
    build: .
    image: nestjs-starter-kit:0.1
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - database
      - redis
    networks:
      - app_net

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    networks:
      - app_net

volumes:
  redis-data:
  starter_kit_db:

networks:
  app_net:
    driver: bridge
