POST http://localhost:8080/posts
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzI5Mzk4MzIxLCJleHAiOjE3MzE5OTAzMjF9.yUwzn1s5g0w8I3eM3q9n9_cWcq1OqOQCZfQ-M0dehrg

{
"title": "test - title",
"content": "test - content",
  "category": {
    "id": 1
  }
}

###
###
GET http://localhost:8080/posts?page=1&limit=3
###
###
GET http://localhost:8080/posts?categories=c1,c2
###
###
GET http://localhost:8080/posts/1
###
###
POST http://localhost:8080/posts/1/vote
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzI5Mzk4MzIxLCJleHAiOjE3MzE5OTAzMjF9.yUwzn1s5g0w8I3eM3q9n9_cWcq1OqOQCZfQ-M0dehrg
###
###
DELETE http://localhost:8080/posts/1/vote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzI5Mzk4MzIxLCJleHAiOjE3MzE5OTAzMjF9.yUwzn1s5g0w8I3eM3q9n9_cWcq1OqOQCZfQ-M0dehrg
###
###
GET http://localhost:8080/posts/1/voted


###
POST http://localhost:8080/users
Content-Type: application/json
x-auth-token: 123456

{
"name": "user6",
"password": "123456"
}

###
###
GET http://localhost:8080/users
###
###
GET http://localhost:8080/users/1
###
###
GET http://localhost:8080/users/6/voted
###
###
PUT http://localhost:8080/users/1/password
Content-Type: application/json

{
"password": "123456",
"newPassword": "123456"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "name": "user1",
  "password": "1234567"
}

###
GET http://localhost:8080/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzI5Mzk4MzIxLCJleHAiOjE3MzE5OTAzMjF9.yUwzn1s5g0w8I3eM3q9n9_cWcq1OqOQCZfQ-M0dehrg


###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "category - name2",
  "alias": "c2"
}

###
POST http://localhost:8080/roles
Content-Type: application/json

{
  "name": "guest",
  "alias": "r3"
}

###
PUT http://localhost:8080/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiaWF0IjoxNzI5Mzk4MzIxLCJleHAiOjE3MzE5OTAzMjF9.yUwzn1s5g0w8I3eM3q9n9_cWcq1OqOQCZfQ-M0dehrg

{
  "roles": [
    {"id":  1},
    {"id":  2}
  ]
}


###
POST http://localhost:8080/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
content-type: text/plain

< /Users/tom/Desktop/temp/nestjs-starter-kit/test.txt
--WebAppBoundary--


###
GET http://localhost:8080/files/1

###
GET http://localhost:8080/cron/stop

###
POST http://localhost:8080/cron
Content-Type: application/json

{
  "name": "test-job",
  "schedule": "3 */10 * * * *"
}

###
DELETE http://localhost:8080/cron/test-job


###
GET http://localhost:8080/cron

###
GET http://localhost:8080/cron/test-job


###
POST http://localhost:8080/queue/add-job
Content-Type: application/json

{
  "task": "test-task"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "name": "user1",
  "password": "1234567"
}