POST http://localhost:3000/posts
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTA3NjI2NCwiZXhwIjoxNzMxNjY4MjY0fQ.H-1c41Eu3v8KSa1SGhF5-8eYE8uhjK1uCLHlGlluioI

{
"title": "test - title",
"content": "test - content"
}


###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/2

###
POST http://localhost:3000/posts/1/vote
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTA3NjI2NCwiZXhwIjoxNzMxNjY4MjY0fQ.H-1c41Eu3v8KSa1SGhF5-8eYE8uhjK1uCLHlGlluioI

###
DELETE http://localhost:3000/posts/3/vote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTA3NjI2NCwiZXhwIjoxNzMxNjY4MjY0fQ.H-1c41Eu3v8KSa1SGhF5-8eYE8uhjK1uCLHlGlluioI

###
GET http://localhost:3000/posts/12/voted

#-----------------------------------------
###
POST http://localhost:3000/users
Content-Type: application/json
x-auth-token: 123456

{
"name": "test - name3",
"password": "123456"
}


###
GET http://localhost:3000/users

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/6

###
GET http://localhost:3000/users/6/voted

###
PUT http://localhost:3000/users/4/password
Content-Type: application/json

{
"password": "1234567",
"newPassword": "1234567"
}

#-----------------------------------------
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "test - name3",
  "password": "1234567"
}

###
GET http://localhost:3000/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTA3NjI2NCwiZXhwIjoxNzMxNjY4MjY0fQ.H-1c41Eu3v8KSa1SGhF5-8eYE8uhjK1uCLHlGlluioI
