POST http://localhost:3000/posts
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTEyNjEzOSwiZXhwIjoxNzMxNzE4MTM5fQ.rc13qXAjLhdHvFW4Vnm4hO02FL9MUoZdE9IiVGoCR64

{
"title": "test - title",
"content": "test - content",
  "category": {
    "id": 1
  }
}


###
GET http://localhost:3000/posts?page=1&limit=3

###
GET http://localhost:3000/posts?categories=c1,c2

###
GET http://localhost:3000/posts/2

###
POST http://localhost:3000/posts/1/vote
Content-Type: application/json
x-auth-token: 123456
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTEyNjEzOSwiZXhwIjoxNzMxNzE4MTM5fQ.rc13qXAjLhdHvFW4Vnm4hO02FL9MUoZdE9IiVGoCR64

###
DELETE http://localhost:3000/posts/3/vote
Content-Type: application/json
Authorization: Bearer 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTEyNjEzOSwiZXhwIjoxNzMxNzE4MTM5fQ.rc13qXAjLhdHvFW4Vnm4hO02FL9MUoZdE9IiVGoCR64

###
GET http://localhost:3000/posts/12/voted

#-----------------------------------------
###
POST http://localhost:3000/users
Content-Type: application/json
x-auth-token: 123456

{
"name": "test - name4",
"password": "123456"
}


###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/6

###
GET http://localhost:3000/users/6/voted

###
PUT http://localhost:3000/users/4/password
Content-Type: application/json

{
"password": "1234567",
"newPassword": "1234567"
}

#-----------------------------------------
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "name": "test - name3",
  "password": "1234567"
}

###
GET http://localhost:3000/auth/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTEyNjEzOSwiZXhwIjoxNzMxNzE4MTM5fQ.rc13qXAjLhdHvFW4Vnm4hO02FL9MUoZdE9IiVGoCR64


###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "category - name1",
  "alias": "c1"
}

###
POST http://localhost:3000/roles
Content-Type: application/json

{
  "name": "guest",
  "alias": "r3"
}

###
PUT http://localhost:3000/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6InRlc3QgLSBuYW1lMyIsImlhdCI6MTcyOTEyNjEzOSwiZXhwIjoxNzMxNzE4MTM5fQ.rc13qXAjLhdHvFW4Vnm4hO02FL9MUoZdE9IiVGoCR64

{
  "roles": [
    {"id":  1},
    {"id":  2}
  ]
}


###
POST http://localhost:3000/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
content-type: text/plain

< /Users/tom/Desktop/temp/nestjs-starter-kit/test.txt
--WebAppBoundary--


###
GET http://localhost:3000/files/2

###
GET http://localhost:3000/cron/stop

###
POST http://localhost:3000/cron
Content-Type: application/json

{
  "name": "test-job",
  "schedule": "3 */10 * * * *"
}

###
DELETE http://localhost:3000/cron/test-job


###
GET http://localhost:3000/cron

###
GET http://localhost:3000/cron/test-job


###
POST http://localhost:3000/queue/add-job
Content-Type: application/json

{
  "task": "test-task"
}